create or replace
PROCEDURE P1_BITACORA (TABLA IN VARCHAR2, RESPUESTA IN OUT INT)
AS

BEGIN
DECLARE V_COUNTER NUMBER; 
BEGIN
SELECT * INTO V_COUNTER FROM BITACORA.TABLA_MODIFICADA = TABLA;

IF V_COUNTER>0 THEN

	SELECT 
		BITACORA.CEDULA,
		BITACORA.FECHA_OPERACION,
		BITACORA.USUARIO_OPERACION,
		BITACORA.MAQUINA_OPERACION,
		BITACORA.TABLA_MODIFICADA,
		BITACORA.TIPO_OPERACION
	FROM
		BITACORA
	WHERE
		BITACORA.TIPO_OPERACION = TABLA;

ELSE
	RESPUESTA := 0;
END IF;
END;
END;
/
create or replace
PROCEDURE P2_BITACORA (FECHA IN DATE, RESPUESTA IN OUT INT)
AS
BEGIN
DECLARE V_COUNTER NUMBER; 
BEGIN
SELECT * INTO V_COUNTER FROM BITACORA.FECHA_OPERACION = FECHA;

IF V_COUNTER>0 THEN

	SELECT 
		BITACORA.CEDULA,
		BITACORA.FECHA_OPERACION,
		BITACORA.USUARIO_OPERACION,
		BITACORA.MAQUINA_OPERACION,
		BITACORA.TABLA_MODIFICADA,
		BITACORA.TIPO_OPERACION
	FROM
		BITACORA
	WHERE
		BITACORA_SEG.FECHA_OPERACION = FECHA;

ELSE
	RESPUESTA := 0;
END IF;
END;
END;
/
create or replace
PROCEDURE P3_BITACORA (OPERACION IN VARCHAR2, RESPUESTA IN OUT INT)
AS
BEGIN
DECLARE V_COUNTER NUMBER; 
BEGIN
SELECT * INTO V_COUNTER FROM BITACORA_SEG.TIPO_OPERACION = OPERACION;

IF V_COUNTER>0 THEN

	SELECT 
		BITACORA.CEDULA,
		BITACORA.FECHA_OPERACION,
		BITACORA.USUARIO_OPERACION,
		BITACORA.MAQUINA_OPERACION,
		BITACORA.TABLA_MODIFICADA,
		BITACORA.TIPO_OPERACION
	FROM
		BITACORA
	WHERE
		BITACORA.TIPO_OPERACION = OPERACION;

ELSE
	RESPUESTA := 0;
END IF;
END;
END;
/
		
		