-- TRIGGER PARA EMPLEADO
CREATE OR REPLACE TRIGGER TR_INS_EMPLEADO BEFORE INSERT ON EMPLEADO 
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_EMPLEADO BEFORE DELETE ON EMPLEADO 
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_EMPLEADO BEFORE UPDATE ON EMPLEADO 
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO',
	   'UPDATE');   
END;
/

--TRIGERS EMPLEADO_PLANTA
CREATE OR REPLACE TRIGGER TR_INS_EMPLANTA BEFORE INSERT ON EMPLEADO_PLANTA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_PLANTA',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_EMPLANTA BEFORE DELETE ON EMPLEADO_PLANTA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_PLANTA',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_EMPLANTA BEFORE UPDATE ON EMPLEADO_PLANTA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_PLANTA',
	   'UPDATE');   
END;
/

--Trigger EMPLEADO_TEMPORAL
CREATE OR REPLACE TRIGGER TR_INS_EMPLEADO_TEMPORAL BEFORE INSERT ON EMPLEADO_TEMPORAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_TEMPORAL',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_EMPLEADO_TEMPORAL BEFORE DELETE ON EMPLEADO_TEMPORAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_TEMPORAL',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_EMPLEADO_TEMPORAL BEFORE UPDATE ON EMPLEADO_TEMPORAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_TEMPORAL',
	   'UPDATE');   
END;
/

--Trigger COORDINADOR_CONTRATO
CREATE OR REPLACE TRIGGER TR_INS_CCONTRATO BEFORE INSERT ON COORDINADOR_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORDINADOR_CONTRATO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_CCONTRATO BEFORE DELETE ON COORDINADOR_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORDINADOR_CONTRATO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_CCONTRATO BEFORE UPDATE ON COORDINADOR_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORDINADOR_CONTRATO',
	   'UPDATE');   
END;
/

--Trigger DIRECTOR_COMERCIAL
CREATE OR REPLACE TRIGGER TR_INS_DIRCMCIAL BEFORE INSERT ON DIRECTOR_COMERCIAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_COMERCIAL',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_DIRCMCIAL BEFORE DELETE ON DIRECTOR_COMERCIAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_COMERCIAL',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_DIRCMCIAL BEFORE UPDATE ON DIRECTOR_COMERCIAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_COMERCIAL',
	   'UPDATE');   
END;
/

--Trigger DIRECTOR_GESTION_HUMANA

CREATE OR REPLACE TRIGGER 	TR_INS_DIRGESHUM BEFORE INSERT ON DIRECTOR_GESTION_HUMANA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_GESTION_HUMANA',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_DIRGESHUM BEFORE DELETE ON DIRECTOR_GESTION_HUMANA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_GESTION_HUMANA',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_DIRGESHUM BEFORE UPDATE ON DIRECTOR_GESTION_HUMANA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_GESTION_HUMANA',
	   'UPDATE');   
END;
/

--Trigger Subgerente
CREATE OR REPLACE TRIGGER TR_INS_SUBGERENT BEFORE INSERT ON SUBGERENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'SUBGERENTE',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_SUBGERENT BEFORE DELETE ON SUBGERENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'SUBGERENTE',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_SUBGERENT BEFORE UPDATE ON SUBGERENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'SUBGERENTE',
	   'UPDATE');   
END;
/

--Trigger COORDINADOR_T_T
CREATE OR REPLACE TRIGGER TR_INS_COORDTYY BEFORE INSERT ON COORDINADOR_T_T
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORDINADOR_T_T',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_COORDTYY BEFORE DELETE ON COORDINADOR_T_T
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORDINADOR_T_T',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_COORDTYY BEFORE UPDATE ON COORDINADOR_T_T
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORDINADOR_T_T',
	   'UPDATE');   
END;
/

--Trigger DIRECTOR_OPERACIONES
CREATE OR REPLACE TRIGGER TR_INS_DOPERAC BEFORE INSERT ON DIRECTOR_OPERACIONES
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_OPERACIONES',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_DOPERAC BEFORE DELETE ON DIRECTOR_OPERACIONES
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_OPERACIONES',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_DOPERAC BEFORE UPDATE ON DIRECTOR_OPERACIONES
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIRECTOR_OPERACIONES',
	   'UPDATE');   
END;
/

-- Trigger EMPLEADO_TELEFONO
CREATE OR REPLACE TRIGGER TR_INS_EMTELS BEFORE INSERT ON EMPLEADO_TELEFONO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_TELEFONO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_EMTELS BEFORE DELETE ON EMPLEADO_TELEFONO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_TELEFONO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_EMTELS BEFORE UPDATE ON EMPLEADO_TELEFONO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADO_TELEFONO',
	   'UPDATE');   
END;
/

--Trigger ACTUALIZACION
CREATE OR REPLACE TRIGGER TR_INS_ACTUAL BEFORE INSERT ON ACTUALIZACION
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULADIR,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_ACTUAL BEFORE DELETE ON ACTUALIZACION
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULADIR,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_ACTUAL BEFORE UPDATE ON ACTUALIZACION
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULADIR,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION',
	   'UPDATE');   
END;
/

--Trigger COMUNICADO 
CREATE OR REPLACE TRIGGER TR_INS_COMUN BEFORE INSERT ON COMUNICADO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULAET,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COMUNICADO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_COMUN BEFORE DELETE ON COMUNICADO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULAET,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COMUNICADO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_COMUN BEFORE UPDATE ON COMUNICADO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULAET,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COMUNICADO',
	   'UPDATE');   
END;
/

--Trigger ASIGNACION_CONTRATO
CREATE OR REPLACE TRIGGER TR_INS_ASIGC BEFORE INSERT ON ASIGNACION_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_CONTRATO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_ASIGC BEFORE DELETE ON ASIGNACION_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_CONTRATO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_ASIGC BEFORE UPDATE ON ASIGNACION_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_CONTRATO',
	   'UPDATE');   
END;
/

-- Trigger CLIENTE
CREATE OR REPLACE TRIGGER TR_INS_CLIEN BEFORE INSERT ON CLIENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CLIENTE',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_CLIEN BEFORE DELETE ON CLIENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CLIENTE',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_CLIEN BEFORE UPDATE ON CLIENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CLIENTE',
	   'UPDATE');   
END;
/

-- Trigger CONTRATO
CREATE OR REPLACE TRIGGER TR_INS_CONT BEFORE INSERT ON CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CONTRATO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_CONT BEFORE DELETE ON CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CONTRATO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_CONT BEFORE UPDATE ON CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CONTRATO',
	   'UPDATE');   
END;
/

--Trigger IMPLEMENTO_SEGURIDAD
CREATE OR REPLACE TRIGGER TR_INS_IMSEG BEFORE INSERT ON IMPLEMENTO_SEGURIDAD
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'IMPLEMENTO_SEGURIDAD',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_IMSEG BEFORE DELETE ON IMPLEMENTO_SEGURIDAD
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'IMPLEMENTO_SEGURIDAD',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_IMSEG BEFORE UPDATE ON IMPLEMENTO_SEGURIDAD
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'IMPLEMENTO_SEGURIDAD',
	   'UPDATE');   
END;
/

--Trigger PROVEEDOR
CREATE OR REPLACE TRIGGER TR_INS_PROV BEFORE INSERT ON PROVEEDOR
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'PROVEEDOR',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_PROV BEFORE DELETE ON PROVEEDOR
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'PROVEEDOR',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_PROV BEFORE UPDATE ON PROVEEDOR
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'PROVEEDOR',
	   'UPDATE');   
END;
/

-- Trigger ASIGNACION_IMPLEMENTO
CREATE OR REPLACE TRIGGER TR_INS_ASMP BEFORE INSERT ON ASIGNACION_IMPLEMENTO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULAET,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_IMPLEMENTO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_ASMP BEFORE DELETE ON ASIGNACION_IMPLEMENTO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULAET,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_IMPLEMENTO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_ASMP BEFORE UPDATE ON ASIGNACION_IMPLEMENTO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULAET,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_IMPLEMENTO',
	   'UPDATE');   
END;
/

--Trigger ACTUALIZACION_IMPLEMENTO
CREATE OR REPLACE TRIGGER TR_INS_ACIMP BEFORE INSERT ON ACTUALIZACION_IMPLEMENTO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION_IMPLEMENTO',
	   'INSERT');   
END;
/
CREATE OR REPLACE TRIGGER TR_DEL_ACIMP BEFORE DELETE ON ACTUALIZACION_IMPLEMENTO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:old.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION_IMPLEMENTO',
	   'DELETE');   
END;
/
CREATE OR REPLACE TRIGGER TR_UPD_ACIMP BEFORE UPDATE ON ACTUALIZACION_IMPLEMENTO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (CEDULA, FECHA_OPERACION, USUARIO_OPERACION, MAQUINA_OPERACION, TABLA_MODIFICADA, TIPO_OPERACION)
VALUES(:new.CEDULA,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION_IMPLEMENTO',
	   'UPDATE');   
END;
/












































