create or replace
PROCEDURE P1_BITACORA (TABLA IN VARCHAR2, RESPUESTA IN OUT INT)
AS

BEGIN
DECLARE V_COUNTER NUMBER; 
BEGIN
SELECT * INTO V_COUNTER FROM BITACORA_SEG.TABLA_MOD = TABLA;

IF V_COUNTER>0 THEN

	SELECT 
		BITACORA_SEG.CEDULAE,
		BITACORA_SEG.FECHA_OPER,
		BITACORA_SEG.USU_OPER,
		BITACORA_SEG.MAQ_OPER,
		BITACORA_SEG.TABLA_MOD,
		BITACORA_SEG.TIPO_OPER
	FROM
		BITACORA_SEG
	WHERE
		BITACORA_SEG.TABLA_MOD = TABLA;

ELSE
	RESPUESTA := 0;
END IF;
END;
END;
/
create or replace
PROCEDURE P2_BITACORA (FECHA IN DATE, RESPUESTA IN OUT INT)
AS
BEGIN
DECLARE V_COUNTER NUMBER; 
BEGIN
SELECT * INTO V_COUNTER FROM BITACORA_SEG.FECHA_OPER = FECHA;

IF V_COUNTER>0 THEN

	SELECT 
		BITACORA_SEG.CEDULAE,
		BITACORA_SEG.FECHA_OPER,
		BITACORA_SEG.USU_OPER,
		BITACORA_SEG.MAQ_OPER,
		BITACORA_SEG.TABLA_MOD,
		BITACORA_SEG.TIPO_OPER
	FROM
		BITACORA_SEG
	WHERE
		BITACORA_SEG.TABLA_MOD = TABLA;

ELSE
	RESPUESTA := 0;
END IF;
END;
END;
/
create or replace
PROCEDURE P3_BITACORA (OPERACION IN VARCHAR2, RESPUESTA IN OUT INT)
AS
BEGIN
DECLARE V_COUNTER NUMBER; 
BEGIN
SELECT * INTO V_COUNTER FROM BITACORA_SEG.TIPO_OPER = OPERACION;

IF V_COUNTER>0 THEN

	SELECT 
		BITACORA_SEG.CEDULAE,
		BITACORA_SEG.FECHA_OPER,
		BITACORA_SEG.USU_OPER,
		BITACORA_SEG.MAQ_OPER,
		BITACORA_SEG.TABLA_MOD,
		BITACORA_SEG.TIPO_OPER
	FROM
		BITACORA_SEG
	WHERE
		BITACORA_SEG.TABLA_MOD = TABLA;

ELSE
	RESPUESTA := 0;
END IF;
END;
END;
/
		
		