-- TRIGGER PARA EMPLEADOS
CREATE OR REPLACE TRIGGER TR_INS_EMPLEADOS BEFORE INSERT ON EMPLEADOS 
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADOS',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_EMPLEADOS BEFORE DELETE ON EMPLEADOS 
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADOS',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_EMPLEADOS BEFORE UPDATE ON EMPLEADOS 
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMPLEADOS',
	   'UPDATE');   
END;


--TRIGERS EMP_PLANTA
CREATE OR REPLACE TRIGGER TR_INS_EMPLANTA BEFORE INSERT ON EMP_PLANTA
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMP_PLANTA',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_EMPLANTA BEFORE DELETE ON EMP_PLANTA
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMP_PLANTA',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_EMPLANTA BEFORE UPDATE ON EMP_PLANTA
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EMP_PLANTA',
	   'UPDATE');   
END;

--Trigger EMP_TEMP
CREATE OR REPLACE TRIGGER TR_INS_EM_TEMP BEFORE INSERT ON EM_TEMP
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EM_TEMP',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_EM_TEMP BEFORE DELETE ON EM_TEMP
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EM_TEMP',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_EM_TEMP BEFORE UPDATE ON EM_TEMP
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EM_TEMP',
	   'UPDATE');   
END;

--Trigger Coord_Contrato
CREATE OR REPLACE TRIGGER TR_INS_CCONTRATO BEFORE INSERT ON COORD_CONTRATO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORD_CONTRATO',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_CCONTRATO BEFORE DELETE ON COORD_CONTRATO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORD_CONTRATO',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_CCONTRATO BEFORE UPDATE ON COORD_CONTRATO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORD_CONTRATO',
	   'UPDATE');   
END;

--Trigger Dir_Comercial
CREATE OR REPLACE TRIGGER TR_INS_DIRCMCIAL BEFORE INSERT ON DIR_COMERCIAL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_COMERCIAL',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_DIRCMCIAL BEFORE DELETE ON DIR_COMERCIAL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_COMERCIAL',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_DIRCMCIAL BEFORE UPDATE ON DIR_COMERCIAL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_COMERCIAL',
	   'UPDATE');   
END;

--Trigger DIR_GESTION_HUM

CREATE OR REPLACE TRIGGER 	TR_INS_DIRGESHUM BEFORE INSERT ON DIR_GESTION_HUM
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_GESTION_HUM',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_DIRGESHUM BEFORE DELETE ON DIR_GESTION_HUM
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_GESTION_HUM',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_DIRGESHUM BEFORE UPDATE ON DIR_GESTION_HUM
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_GESTION_HUM',
	   'UPDATE');   
END;

--Trigger Subgerente

CREATE OR REPLACE TRIGGER TR_INS_SUBGERENT BEFORE INSERT ON SUBGERENTE
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'SUBGERENTE',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_SUBGERENT BEFORE DELETE ON SUBGERENTE
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'SUBGERENTE',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_SUBGERENT BEFORE UPDATE ON SUBGERENTE
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'SUBGERENTE',
	   'UPDATE');   
END;

--Trigger COORD_T_Y_Y

CREATE OR REPLACE TRIGGER TR_INS_COORDTYY BEFORE INSERT ON COORD_T_Y_Y
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORD_T_Y_Y',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_COORDTYY BEFORE DELETE ON COORD_T_Y_Y
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORD_T_Y_Y',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_COORDTYY BEFORE UPDATE ON COORD_T_Y_Y
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COORD_T_Y_Y',
	   'UPDATE');   
END;


--Trigger DIR_OPERACIONES

CREATE OR REPLACE TRIGGER TR_INS_DOPERAC BEFORE INSERT ON DIR_OPERACIONES
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_OPERACIONES',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_DOPERAC BEFORE DELETE ON DIR_OPERACIONES
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_OPERACIONES',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_DOPERAC BEFORE UPDATE ON DIR_OPERACIONES
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'DIR_OPERACIONES',
	   'UPDATE');   
END;

-- Trigger EM_TIENE_TELS
CREATE OR REPLACE TRIGGER TR_INS_EMTELS BEFORE INSERT ON EM_TIENE_TELS
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EM_TIENE_TELS',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_EMTELS BEFORE DELETE ON EM_TIENE_TELS
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EM_TIENE_TELS',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_EMTELS BEFORE UPDATE ON EM_TIENE_TELS
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'EM_TIENE_TELS',
	   'UPDATE');   
END;

--Trigger ACTUALIZACION
CREATE OR REPLACE TRIGGER TR_INS_ACTUAL BEFORE INSERT ON ACTUALIZACION
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_ACTUAL BEFORE DELETE ON ACTUALIZACION
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_ACTUAL BEFORE UPDATE ON ACTUALIZACION
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTUALIZACION',
	   'UPDATE');   
END;

--Trigger COMUNICADO 
CREATE OR REPLACE TRIGGER TR_INS_COMUN BEFORE INSERT ON COMUNICADO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COMUNICADO',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_COMUN BEFORE DELETE ON COMUNICADO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COMUNICADO',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_COMUN BEFORE UPDATE ON COMUNICADO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'COMUNICADO',
	   'UPDATE');   
END;

--Trigger ASIGNACION_C
CREATE OR REPLACE TRIGGER TR_INS_ASIGC BEFORE INSERT ON ASIGNACION_C
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_C',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_ASIGC BEFORE DELETE ON ASIGNACION_C
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_C',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_ASIGC BEFORE UPDATE ON ASIGNACION_C
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIGNACION_C',
	   'UPDATE');   
END;

-- Trigger CLIENTE
CREATE OR REPLACE TRIGGER TR_INS_CLIEN BEFORE INSERT ON CLIENTE
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CLIENTE',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_CLIEN BEFORE DELETE ON CLIENTE
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CLIENTE',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_CLIEN BEFORE UPDATE ON CLIENTE
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CLIENTE',
	   'UPDATE');   
END;

-- Trigger CONTRATO

CREATE OR REPLACE TRIGGER TR_INS_CONT BEFORE INSERT ON CONTRATO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CONTRATO',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_CONT BEFORE DELETE ON CONTRATO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CONTRATO',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_CONT BEFORE UPDATE ON CONTRATO
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'CONTRATO',
	   'UPDATE');   
END;

--Trigger IMPL_SEGURIDAD
CREATE OR REPLACE TRIGGER TR_INS_IMSEG BEFORE INSERT ON IMPL_SEGURIDAD
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'IMPL_SEGURIDAD',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_IMSEG BEFORE DELETE ON IMPL_SEGURIDAD
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'IMPL_SEGURIDAD',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_IMSEG BEFORE UPDATE ON IMPL_SEGURIDAD
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'IMPL_SEGURIDAD',
	   'UPDATE');   
END;

--Trigger PROVEEDOR
CREATE OR REPLACE TRIGGER TR_INS_PROV BEFORE INSERT ON PROVEEDOR
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'PROVEEDOR',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_PROV BEFORE DELETE ON PROVEEDOR
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'PROVEEDOR',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_PROV BEFORE UPDATE ON PROVEEDOR
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'PROVEEDOR',
	   'UPDATE');   
END;

-- Trigger ASIG_IMPL
CREATE OR REPLACE TRIGGER TR_INS_ASMP BEFORE INSERT ON ASIG_IMPL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIG_IMPL',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_ASMP BEFORE DELETE ON ASIG_IMPL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIG_IMPL',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_ASMP BEFORE UPDATE ON ASIG_IMPL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ASIG_IMPL',
	   'UPDATE');   
END;

--Trigger ACTU_IMPL
CREATE OR REPLACE TRIGGER TR_INS_ACIMP BEFORE INSERT ON ACTU_IMPL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTU_IMPL',
	   'INSERT');   
END;

CREATE OR REPLACE TRIGGER TR_DEL_ACIMP BEFORE DELETE ON ACTU_IMPL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:old.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTU_IMPL',
	   'DELETE');   
END;

CREATE OR REPLACE TRIGGER TR_UPD_ACIMP BEFORE UPDATE ON ACTU_IMPL
BEGIN
INSERT INTO BITACORA_SEG (CEDULAE, FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(:new.CEDULAE,
       SELECT SYSDATE FROM DUAL,
       SELECT SYS_CONTEXT('SESSION_USER') FROM DUAL,
       SELECT SYS_CONTEXT('HOST') FROM DUAL,
       'ACTU_IMPL',
	   'UPDATE');   
END;













































