-- TRIGGER PARA EMPLEADO

CREATE OR REPLACE TRIGGER TR_INS_EMPLEADO BEFORE INSERT ON EMPLEADOS
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG(FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(SYSDATE,
       USER,
       NULL,
       'EMPLEADO',
	   'INSERT'
     newval);   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_EMPLEADO BEFORE DELETE ON EMPLEADOS 
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
VALUES(SYSDATE,
       USER,
       NULL,
       'EMPLEADO',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_EMPLEADO BEFORE UPDATE ON EMPLEADOS 
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'EMPLEADO',
	   'UPDATE');   
END;
/

--TRIGERS EMP_PLANTA
CREATE OR REPLACE TRIGGER TR_INS_EMPLANTA BEFORE INSERT ON EMP_PLANTA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'EMP_PLANTA',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_EMPLANTA BEFORE DELETE ON EMP_PLANTA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'EMP_PLANTA',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_EMPLANTA BEFORE UPDATE ON EMP_PLANTA
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'EMP_PLANTA',
	   'UPDATE');   
END;
/

--Trigger EMPLEADO_TEMPORAL
CREATE OR REPLACE TRIGGER TR_INS_EMPLEADO_TEMPORAL BEFORE INSERT ON EMP_TEMP
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'EMPLEADO_TEMPORAL',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_EMPLEADO_TEMPORAL BEFORE DELETE ON EMP_TEMP
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'EMPLEADO_TEMPORAL',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_EMPLEADO_TEMPORAL BEFORE UPDATE ON EMP_TEMP
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'EMPLEADO_TEMPORAL',
	   'UPDATE');   
END;
/

--Trigger COORDINADOR_CONTRATO
CREATE OR REPLACE TRIGGER TR_INS_CCONTRATO BEFORE INSERT ON COORD_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COORDINADOR_CONTRATO',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_CCONTRATO BEFORE DELETE ON COORD_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COORDINADOR_CONTRATO',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_CCONTRATO BEFORE UPDATE ON COORD_CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COORDINADOR_CONTRATO',
	   'UPDATE');   
END;
/

--Trigger DIR_COMERCIAL
CREATE OR REPLACE TRIGGER TR_INS_DIRCMCIAL BEFORE INSERT ON DIR_COMERCIAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_COMERCIAL',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_DIRCMCIAL BEFORE DELETE ON DIR_COMERCIAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_COMERCIAL',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_DIRCMCIAL BEFORE UPDATE ON DIR_COMERCIAL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_COMERCIAL',
	   'UPDATE');   
END;
/

--Trigger DIR_GESTION_HUM

CREATE OR REPLACE TRIGGER 	TR_INS_DIRGESHUM BEFORE INSERT ON DIR_GESTION_HUM
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_GESTION_HUM',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_DIRGESHUM BEFORE DELETE ON DIR_GESTION_HUM
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_GESTION_HUM',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_DIRGESHUM BEFORE UPDATE ON DIR_GESTION_HUM
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_GESTION_HUM',
	   'UPDATE');   
END;
/

--Trigger Subgerente
CREATE OR REPLACE TRIGGER TR_INS_SUBGERENT BEFORE INSERT ON SUBGERENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'SUBGERENTE',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_SUBGERENT BEFORE DELETE ON SUBGERENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'SUBGERENTE',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_SUBGERENT BEFORE UPDATE ON SUBGERENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'SUBGERENTE',
	   'UPDATE');   
END;
/

--Trigger COORD_T_Y_T
CREATE OR REPLACE TRIGGER TR_INS_COORDTYY BEFORE INSERT ON COORD_T_Y_T
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COORD_T_Y_T',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_COORDTYY BEFORE DELETE ON COORD_T_Y_T
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COORD_T_Y_T',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_COORDTYY BEFORE UPDATE ON COORD_T_Y_T
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COORD_T_Y_T',
	   'UPDATE');   
END;
/

--Trigger DIR_OPERACIONES
CREATE OR REPLACE TRIGGER TR_INS_DOPERAC BEFORE INSERT ON DIR_OPERACIONES
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_OPERACIONES',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_DOPERAC BEFORE DELETE ON DIR_OPERACIONES
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_OPERACIONES',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_DOPERAC BEFORE UPDATE ON DIR_OPERACIONES
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'DIR_OPERACIONES',
	   'UPDATE');   
END;
/

-- Trigger TELS_EMP
CREATE OR REPLACE TRIGGER TR_INS_EMTELS BEFORE INSERT ON TELS_EMP
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'TELS_EMP',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_EMTELS BEFORE DELETE ON TELS_EMP
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'TELS_EMP',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_EMTELS BEFORE UPDATE ON TELS_EMP
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'TELS_EMP',
	   'UPDATE');   
END;
/

--Trigger ACTUALIZACION
CREATE OR REPLACE TRIGGER TR_INS_ACTUAL BEFORE INSERT ON ACTUALIZACION
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ACTUALIZACION',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_ACTUAL BEFORE DELETE ON ACTUALIZACION
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ACTUALIZACION',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_ACTUAL BEFORE UPDATE ON ACTUALIZACION
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ACTUALIZACION',
	   'UPDATE');   
END;
/

--Trigger COMUNICADO 
CREATE OR REPLACE TRIGGER TR_INS_COMUN BEFORE INSERT ON COMUNICADO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COMUNICADO',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_COMUN BEFORE DELETE ON COMUNICADO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COMUNICADO',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_COMUN BEFORE UPDATE ON COMUNICADO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'COMUNICADO',
	   'UPDATE');   
END;
/

--Trigger ASIGNACION_C
CREATE OR REPLACE TRIGGER TR_INS_ASIGC BEFORE INSERT ON ASIGNACION_C
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ASIGNACION_C',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_ASIGC BEFORE DELETE ON ASIGNACION_C
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ASIGNACION_C',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_ASIGC BEFORE UPDATE ON ASIGNACION_C
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ASIGNACION_C',
	   'UPDATE');   
END;
/

-- Trigger CLIENTE
CREATE OR REPLACE TRIGGER TR_INS_CLIEN BEFORE INSERT ON CLIENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'CLIENTE',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_CLIEN BEFORE DELETE ON CLIENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'CLIENTE',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_CLIEN BEFORE UPDATE ON CLIENTE
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'CLIENTE',
	   'UPDATE');   
END;
/

-- Trigger CONTRATO
CREATE OR REPLACE TRIGGER TR_INS_CONT BEFORE INSERT ON CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'CONTRATO',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_CONT BEFORE DELETE ON CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'CONTRATO',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_CONT BEFORE UPDATE ON CONTRATO
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'CONTRATO',
	   'UPDATE');   
END;
/

--Trigger IMPL_SEGURIDAD
CREATE OR REPLACE TRIGGER TR_INS_IMSEG BEFORE INSERT ON IMPL_SEGURIDAD
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'IMPL_SEGURIDAD',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_IMSEG BEFORE DELETE ON IMPL_SEGURIDAD
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'IMPL_SEGURIDAD',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_IMSEG BEFORE UPDATE ON IMPL_SEGURIDAD
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'IMPL_SEGURIDAD',
	   'UPDATE');   
END;
/

--Trigger PROVEEDOR
CREATE OR REPLACE TRIGGER TR_INS_PROV BEFORE INSERT ON PROVEEDOR
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'PROVEEDOR',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_PROV BEFORE DELETE ON PROVEEDOR
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'PROVEEDOR',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_PROV BEFORE UPDATE ON PROVEEDOR
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'PROVEEDOR',
	   'UPDATE');   
END;
/

-- Trigger ASIG_IMPL

CREATE OR REPLACE TRIGGER TR_INS_ASMP BEFORE INSERT ON ASIG_IMPL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ASIG_IMPL',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_ASMP BEFORE DELETE ON ASIG_IMPL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ASIG_IMPL',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_ASMP BEFORE UPDATE ON ASIG_IMPL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ASIG_IMPL',
	   'UPDATE');   
END;
/

--Trigger ACTU_IMPL
CREATE OR REPLACE TRIGGER TR_INS_ACIMP BEFORE INSERT ON ACTU_IMPL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ACTU_IMPL',
	   'INSERT');   
END;
/

CREATE OR REPLACE TRIGGER TR_DEL_ACIMP BEFORE DELETE ON ACTU_IMPL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ACTU_IMPL',
	   'DELETE');   
END;
/

CREATE OR REPLACE TRIGGER TR_UPD_ACIMP BEFORE UPDATE ON ACTU_IMPL
FOR EACH ROW 
BEGIN
INSERT INTO BITACORA_SEG (FECHA_OPER, USU_OPER, MAQ_OPER, TABLA_MOD, TIPO_OPER)
 VALUES(SYSDATE,
       USER,
       NULL,
       'ACTU_IMPL',
	   'UPDATE');   
END;
/












































